### ISSUE TITLE
[REVIEW]: lowercase alias

### ISSUE THREAD

**Issue by med-oc** [ACCESS-NRI/med-reviews#16]
**Submitting author:** @max-anu (<a href="http://orcid.org/0009-0003-1611-9516">Max Proft</a>)
**Repository:** https://github.com/max-anu/example-medportal2
**Branch with paper.md** (empty if default branch): 
**Version:** v1.0
**Editor:** @max-anu
**Reviewers:** @max-anu
**Archive:** 10.21105/medportal.00016

## Status

[![status](https://medportal-dev-6a745f452687.herokuapp.com/papers/a1455e4a96def93434361318737afd00/status.svg)](https://medportal-dev-6a745f452687.herokuapp.com/papers/a1455e4a96def93434361318737afd00)

Status badge code:

```
HTML: <a href="https://medportal-dev-6a745f452687.herokuapp.com/papers/a1455e4a96def93434361318737afd00"><img src="https://medportal-dev-6a745f452687.herokuapp.com/papers/a1455e4a96def93434361318737afd00/status.svg"></a>
Markdown: [![status](https://medportal-dev-6a745f452687.herokuapp.com/papers/a1455e4a96def93434361318737afd00/status.svg)](https://medportal-dev-6a745f452687.herokuapp.com/papers/a1455e4a96def93434361318737afd00)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/max-anu/example-medportal2" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@max-anu, your review will be checklist based. Each of you will have a separate checklist that you should update when carrying out your review.
First of all you need to run this command in a separate comment to create the checklist:

```
@med-oc generate my checklist
```

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @max-anu know.

✨ **Please start on your review when you are able, and be sure to complete your review in the next six weeks, at the very latest** ✨ 

## Checklists

  @max-anu, please create your checklist typing: `@med-oc generate my checklist`

**Comment by med-oc** [comment]
Hello humans, I'm @med-oc, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@med-oc help
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@med-oc generate pdf
```

**Comment by max-anu** [comment]
@med-oc set 10.21105/medportal.00014 as archive

**Comment by med-oc** [comment]
Done! archive is now 10.21105/medportal.00014

**Comment by max-anu** [comment]
@med-oc set 10.21105/medportal.00016 as archive

**Comment by med-oc** [comment]
Done! archive is now 10.21105/medportal.00016

**Comment by max-anu** [comment]
@med-oc accept

**Comment by med-oc** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by med-oc** [comment]
**Ensure proper citation** by uploading a plain text CITATION.cff file to the default branch of your repository.

If using GitHub, a *Cite this repository* menu will appear in the About section, containing both APA and BibTeX formats. When exported to Zotero using a browser plugin, Zotero will automatically create an entry using the information contained in the .cff file.

You can copy the contents for your CITATION.cff file here:

<details><summary><strong>CITATION.cff</strong></summary>
<p>

```
cff-version: "1.2.0"
authors:
- family-names: Kerr
  given-names: Cliff C.
  orcid: "https://orcid.org/0000-0003-2517-2354"
- family-names: Sanz-Leon
  given-names: Paula
  orcid: "https://orcid.org/0000-0002-1545-6380"
- family-names: Abeysuriya
  given-names: Romesh G.
  orcid: "https://orcid.org/0000-0002-9618-6457"
- family-names: Chadderdon
  given-names: George L.
  orcid: "https://orcid.org/0000-0002-3034-2330"
- family-names: Harbuz
  given-names: Vlad-Ştefan
- family-names: Saidi
  given-names: Parham
- family-names: Mar Quiroga
  given-names: Maria
  name-particle: del
  orcid: "https://orcid.org/0000-0002-8943-2808"
- family-names: Martin-Hughes
  given-names: Rowan
  orcid: "https://orcid.org/0000-0002-3724-2412"
- family-names: Kelly
  given-names: Sherrie L.
  orcid: "https://orcid.org/0000-0002-6232-5586"
- family-names: Cohen
  given-names: Jamie A.
  orcid: "https://orcid.org/0000-0002-8479-1860"
- family-names: Stuart
  given-names: Robyn M.
  orcid: "https://orcid.org/0000-0001-6867-9265"
- family-names: Nachesa
  given-names: Anna
contact:
- family-names: Kerr
  given-names: Cliff C.
  orcid: "https://orcid.org/0000-0003-2517-2354"
doi: 10.21105/medportal.00016
message: If you use this software, please cite our article in the
  Journal of Open Source Software.
preferred-citation:
  authors:
  - family-names: Kerr
    given-names: Cliff C.
    orcid: "https://orcid.org/0000-0003-2517-2354"
  - family-names: Sanz-Leon
    given-names: Paula
    orcid: "https://orcid.org/0000-0002-1545-6380"
  - family-names: Abeysuriya
    given-names: Romesh G.
    orcid: "https://orcid.org/0000-0002-9618-6457"
  - family-names: Chadderdon
    given-names: George L.
    orcid: "https://orcid.org/0000-0002-3034-2330"
  - family-names: Harbuz
    given-names: Vlad-Ştefan
  - family-names: Saidi
    given-names: Parham
  - family-names: Mar Quiroga
    given-names: Maria
    name-particle: del
    orcid: "https://orcid.org/0000-0002-8943-2808"
  - family-names: Martin-Hughes
    given-names: Rowan
    orcid: "https://orcid.org/0000-0002-3724-2412"
  - family-names: Kelly
    given-names: Sherrie L.
    orcid: "https://orcid.org/0000-0002-6232-5586"
  - family-names: Cohen
    given-names: Jamie A.
    orcid: "https://orcid.org/0000-0002-8479-1860"
  - family-names: Stuart
    given-names: Robyn M.
    orcid: "https://orcid.org/0000-0001-6867-9265"
  - family-names: Nachesa
    given-names: Anna
  date-published: 2023-08-18
  doi: 10.00000/medportal.00016
  issn: 2475-9066
  issue: 1
  journal: Journal of Open Source Software
  publisher:
    name: Open Journals
  start: 16
  title: "Example 2: Simplifying scientific software in Python"
  type: article
  url: "https://joss.theoj.org/papers/10.00000/medportal.00016"
  volume: 1
title: "Example 2: Simplifying scientific software in Python"

```

</p>
</details>

If the repository is not hosted on GitHub, a .cff file can still be uploaded to set your preferred citation. Users will be able to manually copy and paste the citation.

Find more information on .cff files [here](https://github.com/citation-file-format/citation-file-format/blob/main/README.md) and [here](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-citation-files).
